### ISSUE TITLE
[BUG] `deno check` error: `Type 'string' is not assignable to type '"plain_text"'`

### ISSUE THREAD

**Issue by arnaubt** [slackapi/deno-slack-sdk#380]
**The `deno-slack` versions**

```
"deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.2/",
"deno-slack-api/": "https://deno.land/x/deno_slack_api@2.8.0/",
```

**Deno runtime version**

```
deno 2.0.1 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

**OS info**

```
ProductName:            macOS
ProductVersion:         14.3.1
BuildVersion:           23D60
Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
```

**Describe the bug**

While implementing a Block suggestion handler (with `addBlockSuggestionHandler`) I'm getting the following error when running `deno check`:
```sh
error: TS2345 [ERROR]: Argument of type '({ body, client, env }: { body: Record<string, string>; client: SlackAPIClient; env: Env; }) => Promise<{ options: { value: string; text: { type: string; text: string; emoji: boolean; }; }[]; }>' is not assignable to parameter of type '(context: SuggestionContext<FunctionRuntimeParameters<{ jira_id: { type: "string"; description: string; }; }, never[]>>) => BlockSuggestionHandlerResponse | Promise<...>'.
  Type 'Promise<{ options: { value: string; text: { type: string; text: string; emoji: boolean; }; }[]; }>' is not assignable to type 'BlockSuggestionHandlerResponse | Promise<BlockSuggestionHandlerResponse>'.
    Type 'Promise<{ options: { value: string; text: { type: string; text: string; emoji: boolean; }; }[]; }>' is not assignable to type 'Promise<BlockSuggestionHandlerResponse>'.
      Type '{ options: { value: string; text: { type: string; text: string; emoji: boolean; }; }[]; }' is not assignable to type 'BlockSuggestionHandlerResponse'.
        Type '{ options: { value: string; text: { type: string; text: string; emoji: boolean; }; }[]; }' is not assignable to type 'BlockSuggestionHandlerOptionsResponse'.
          Types of property 'options' are incompatible.
            Type '{ value: string; text: { type: string; text: string; emoji: boolean; }; }[]' is not assignable to type 'MenuOption[]'.
              Type '{ value: string; text: { type: string; text: string; emoji: boolean; }; }' is not assignable to type 'MenuOption'.
                The types of 'text.type' are incompatible between these types.
                  Type 'string' is not assignable to type '"plain_text"'.
```

**Steps to reproduce**

I'm using the following return type for the `addBlockSuggestionHandler` function argument:

```
  return {
    options: itemList.map((v) => ({
      value: v,
      text: { type: "plain_text", text: v, emoji: false },
    })),
  };
```

**Expected result**

**Actual result**

When triggering the handler with an `external_select` I can see from the logs the handler being called, but no results are displayed. There aren't any errors either.

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by arnaubt** [comment]
@filmaj @zimeg @WilliamBergamin Any help here would be greatly appreciated 😄

**Comment by WilliamBergamin** [comment]
Hi @arnaubt thanks for writing in 💯 

Would yo be able to provide more source code so I can try to reproduce this error?

What is the type of `v` I think it must be a string 🤔 I also don't think you need to include `emoji: false`

**Comment by arnaubt** [comment]
Below is the full code. You're correct, `v` is a string. And the emoji option probably came from a copy-paste, but the issue remains without it.
```typescript
// deno-lint-ignore-file no-unused-vars
import type { Env, SlackAPIClient } from "deno-slack-sdk/types.ts";
import { Datadog } from "../libs/datadog.ts";

export const SuggestDatadogService = async ({ body, client, env }: {
  body: Record<string, string>;
  client: SlackAPIClient;
  env: Env;
}) => {
  const datadog = new Datadog(env);
  const serviceResponse = await datadog.getServices(); // https://api.datadoghq.eu/api/v2/services/definitions
  const services = await serviceResponse.json();

  const serviceList: Array<string> = services.data.map((
    v: { attributes: { schema: { "dd-service": string } } },
  ) => v.attributes.schema["dd-service"]);

  return {
    options: serviceList.map((v) => ({
      value: v,
      text: { type: "plain_text", text: v },
    })),
  };
};
```

And here's the code for attaching the handler function. Nothing fancy as you can see.
```typescript
...
).addBlockSuggestionHandler(
  "service_name",
  SuggestDatadogService,
)
```

**Comment by WilliamBergamin** [comment]
I'm unable to reproduce your error with the following BlockSuggestionHandler everything works as expected

```ts
.addBlockSuggestionHandler(["service_name"], () => {
  return {
    options: [{
      value: "v1",
      text: { type: "plain_text", text: "v1" },
    }, {
      value: "v2",
      text: { type: "plain_text", text: "v2" },
    }, {
      value: "v3",
      text: { type: "plain_text", text: "v3" },
    }],
  };
});
```

From the typescript error posted above it seems like the returned type of `serviceList.map((v) ...` does not match the expect `options` type format. Your data parsing may not be behaving as you expect it 🤔 

You can run your app using `slack run -vv` to get all the information sent between slack and your app, let me know if you can share any errors related to block suggestions

**Comment by filmaj** [comment]
@arnaubt first question: is the issue you would like resolved the TypeScript compilation error, or the runtime error you described under the "Actual Result" section of your original issue submission?

For the TS issue, I believe the issue is that in your code, your suggestion handler has no function return type defined, so TS attempts to infer the return type and match it against the expected return type for Block Suggestion handlers. A few approaches that may help:

1. Define your suggestion handler "inline" within the call `addBlockSuggestionHandler`, just like in the example @WilliamBergamin posted. This way, the expected type for the handler will be applied to your function, _including_ the return type. Understandably, if you want to organize your functions in a more modular way across several files, this may not be desirable. Options 2 and 3 below should work for you in these cases.
2. Assign a type to the entire exported function, using the `BlockSuggestionHandler` type provided by the deno-slack-sdk. The nice thing about this approach is you don't need to type the arguments anymore, as those types are defined by the handler type. The reference to `MyCustomFunction` below should point to the variable or export housing the relevant `SlackFunction` instance. Something like:
```typescript
export const SuggestDatadogService: BlockSuggestionHandler<typeof MyCustomFunction.definition> = async ({ body, client, env }) => {
```
3. Assign a return type to your exported function. You can use the `ReturnType` utility type in combination with the `BlockSuggestionHandler` type from option 2 to accomplish this. I think this is sub-par to option 2, as it is more verbose due to still needing to manually type the arguments yourself. Something like:
```typescript
export const SuggestDatadogService = async ({ body, client, env }: {
  body: Record<string, string>;
  client: SlackAPIClient;
  env: Env;
}): ReturnType<BlockSuggestionHandler<typeof MyCustomFunction.definition>> => {
```
For option 3, you may also need to potentially wrap the return type in a `Promise<>` type, if your method is async.

My suggestion would be to try option 2.

Hope that helps! Let us know if you have any further trouble.

**Comment by arnaubt** [comment]
Thank you very much @filmaj and @WilliamBergamin!

Adding the required type to the exported function was enough to resolve the linting issue. But unfortunately the runtime one remains.
As I mentioned originally, the handler function works well (judging by the logs), but the form field in Slack doesn't display any results. After a brief wait it displays "Noting could be found". In the logs I can see the following too:

```shell
[2024-11-19 17:06:34] LocalServer.Listen errored: websocket: close 1006 (abnormal closure): unexpected EOF
[2024-11-19 17:06:34] Sending WebSocket Close control message
[2024-11-19 17:06:34] LocalServer.Start closing websocket TCP connection
[2024-11-19 17:06:34] Activity watcher context canceled, returning.
[2024-11-19 17:06:34] File watcher context canceled, returning.
```

For context, the reason I ended up using an interactive handler was due to the size of the list (more than 100). Could that be causing the issue?

**Comment by filmaj** [comment]
@arnaubt yes that could be it: there is a 100 maximum number of elements possible to return as part of suggestion handlers.  See the docs on this [here](https://api.slack.com/reference/block-kit/block-elements#external_select). I recall having trouble with this myself a while ago... try a low number of options, like 5. IIRC in the past I had trouble rendering more than, for example, 7 options.

Another potential issue is that these suggestion handlers must return within 3 seconds of being invoked; since you are calling an external API, it may be useful to drop some timing logs to make sure that is the case.

**Comment by arnaubt** [comment]
That was it! Limiting the values to a lower number finally made it work. Thanks a lot @filmaj!

Will you adjust the docs to reflect this behaviour?
