### ISSUE TITLE
How to trigger registered workflow?

### ISSUE THREAD

**Issue by kuboon** [slackapi/deno-slack-sdk#76]
I read [manifest.md](https://github.com/slackapi/deno-slack-sdk/blob/06282caa893b95882d7188ca58c6b9f5ee93067b/docs/workflows.md) and successfully installed my own manifest.
I checked it under "App manifest" page (https://xxx.slack.com/apps/xxxx-xxxx?settings=1&tab=settings)

But I couldn't find it in my slack shortcuts menu nor workflow builder.

How can I trigger my registered workflow?

**Comment by seratch** [comment]
Hi @kuboon, thanks for writing in! In this SDK project, we are actively working on the new features that are coming in the near future. Those features are not yet available for you at this moment but they will come soon! Stay tuned for more updates on the next-gen platform.

**Comment by shapirone** [comment]
Hello @kuboon, thanks for your patience! Documentation on adding and using triggers can be found on our doc site at https://api.slack.com/future/triggers

**Comment by ftr-lwilson** [comment]
Hi there!

I see in the mentioned documentation with a link trigger, we can "invoke it with a slash command via the shortcut menu:
https://api.slack.com/automation/triggers/link
> They can be invoked in other ways as well. You can:
> - add the link trigger as a bookmark in a channel, then select it
> - invoke it with a slash command via the [Shortcut menu](https://api.slack.com/interactivity/shortcuts/using#shortcut_types)
> - create it as a [workflow button](https://api.slack.com/automation/triggers/link#workflow_buttons), then click the button

I have created a link trigger for my app, but I can't figure out how to invoke it via a slash command and it does not appear in the shortcut menu. Is there something extra I need to do in order to enable this functionality?

Cheers, Luke.
